#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u inference.py "$@"

# The previous version of this file was commented-out and follows below:
#
# python -u train.py "$@"
# 
# # The previous version of this file was commented-out and follows below:
# #
# # python -u train_fine_tuning.py "$@"
# # 
# # # The previous version of this file was commented-out and follows below:
# # #
# # # python -u train.py "$@"
# # # 
# # # # The previous version of this file was commented-out and follows below:
# # # #
# # # # python -u inference.py "$@"
# # # # 
# # # # # The previous version of this file was commented-out and follows below:
# # # # #
# # # # # python -u train_word_phon.py "$@"
# # # # # 
# # # # # # The previous version of this file was commented-out and follows below:
# # # # # #
# # # # # # python -u train_sen_phon.py "$@"
# # # # # # 
# # # # # 
# # # # 
# # # 
# # 
# 
